from PySide import QtCore, QtGui

THUMB_WIDTH = 70
THUMB_HIEGHT = 40
MARGIN = 5
ROW_HEIGHT = 30
ROW_HEIGHT_VERSION = 50
CHECKBOX_WIDTH = 25

BORDER_COLOR_FOR_DELEGATE = "#3e4041"

HEADER_HEIGHT = 25

GROUP_HEADER = QtCore.Qt.UserRole + 1
LATEST_VERSION = QtCore.Qt.UserRole + 2
NODE_ID = QtCore.Qt.UserRole + 3

LIMIT = 25